hyperledger/fabric-contract-api-go

.azure-pipelines/Dockerfile, .azure-pipelines/azure-pipelines.yml, .azure-pipelines/resources/license-config.json, .azure-pipelines/resources/license.txt
Cleaned up license checking whilst pruning yml
Signed-off-by: Andrew Hurt <andrew.hurt1@ibm.com>
=> Move Godog to docker image

CODE_OF_CONDUCT.md, CONTRIBUTING.md
[[FABCAG-2]](https://jira.hyperledger.org/browse/FABCAG-2)
Remedies lack of contributor guide and code of conduct
=> [FABCAG-2] add code of conduct and contrib guide

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/scripts/tutorial-checks.sh, README.md, tutorials/README.md, tutorials/getting-started.md, tutorials/managing-objects.md, tutorials/using-advanced-features.md
- Add three tutorials
- Update readme to include link to tutorials
- Add script to check all tutorials content sections have valid sections
=> [FABCAG-5] Add tutorials and checks

CHANGELOG.md, README.md, go.mod, go.sum
- Removes warning from README
- Updates changelog
=> Preparing for release v2.0.0

.azure-pipelines/azure-pipelines.yml, .github/RELEASE_CHECKLIST.md, CHANGELOG.md, COMPATIBILITY.md, README.md
- Sets version number as 1.0.0
- Updates read me to make clear of fabric 2.0 support
- Updates azure to run build on tagged
=> Prepare release 1.0.0

README.md
Add section to readme on raising issues
=> [FABCAG-25] add details about JIRA to readme

tutorials/managing-objects.md
Update link to using advanced features in prereqs of complex objects tutorial
=> [FABCAG-26] fix prereqs link

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/install_deps.yml, .gitignore, go.mod, go.sum
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
=> Update GoDog Repo Reference

.azure-pipelines/install_deps.yml, .gitignore, COMPATIBILITY.md, README.md, go.mod, go.sum
Signed-off-by: heatherlp <heatherpollard0@gmail.com>
=> FABCAG-27 Support fabric v2.1

CHANGELOG.md
Updates changelog for release v1.1.0
=> Preparing for release v1.1.0

MAINTAINERS.md
Signed-off-by: heatherlp <heatherpollard0@gmail.com>
=> Add MAINTAINERS.md file and nominate James Taylor as a maintainer

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/install_deps.yml
=> Fix build failures

metadata/schema.go, metadata/schema_test.go
Add if to select only before comma in json tags as is done with the metadata tag
=> [FABCAG-31] update to use only first part of JSON tag

.azure-pipelines/azure-pipelines.yml, go.mod
Bump Go to align with Fabric to a support Go version
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
=> Bump Go Version

CHANGELOG.md
=> Preparing for release v1.1.1

metadata/metadata.go, metadata/metadata_test.go
Signed-off-by: Kestutis Gudynas <44440041+kemi04@users.noreply.github.com>
=> [FABCN-439] Metadata issue fixed

MAINTAINERS.md
Update maintainers file to swap awjh-ibm for awjh
=> update maintainers file

MAINTAINERS.md
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
=> Request for maintainer status

.github/workflows/build.yml
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
=> Single simple workflow to enable gha

.dockerignore, .github/workflows/build.yml, ci/license-config.json, contractapi/contract_chaincode.go, integrationtest/Dockerfile, integrationtest/chaincode/simple/Dockerfile, integrationtest/chaincode/simple/go.mod, integrationtest/cucumber.js, integrationtest/package-lock.json, integrationtest/package.json
Automatically start chaincode in sever mode if CHAINCODE_SERVER_ADDRESS and CORE_CHAINCODE_ID_NAME environment variables are set
=> Simplify CCaaS support

.github/workflows/vulnerability-scan.yml
=> Add nightly security vulnerability scan

.github/workflows/vulnerability-scan.yml
=> Add workflow_dispatch to vulnerability scan build

CHANGELOG.md
=> Preparing for release v1.2.0

.github/workflows/vulnerability-scan.yml
=> Use latest Go patch level for vulnerability scan

go.mod, go.sum
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
=> Update text dependency

integrationtest/package-lock.json, integrationtest/package.json
Update to latest fabric-chaincode-integration to pick up new grpc-js dependency.
=> Update test dependencies to address CVE-2024-37168

integrationtest/package-lock.json
Run 'npm audit fix' to update elliptic and axios in integration tests.
=> Bump elliptic and axios in integration test

integrationtest/package-lock.json
Bump integrationtest elliptic node dependency to 6.6.0.
=> Bump integrationtest elliptic node dependency to 6.6.0

internal/transaction_handler.go, internal/types_handler.go, metadata/schema.go
use errors.New to replace fmt.Errorf with no parameters
=> chore: use errors.New to replace fmt.Errorf with no parameters

contractapi/contract_chaincode.go, contractapi/contract_chaincode_test.go, go.mod, go.sum, integrationtest/chaincode/advancedtypes/go.mod, integrationtest/chaincode/advancedtypes/go.sum, integrationtest/chaincode/private/go.mod, integrationtest/chaincode/private/go.sum, integrationtest/chaincode/simple/go.mod, integrationtest/chaincode/simple/go.sum, integrationtest/chaincode/transactionhooks/go.mod, integrationtest/chaincode/transactionhooks/go.sum, internal/contract_function.go, internal/functionaltests/contracts/simplecontract/simplecontract.go, internal/types/types.go, metadata/schema.go, metadata/schema_test.go, serializer/json_transaction_serializer.go
Pass []byte directly instead of treating as a JSON array. The correct OpenAPI type for []byte is type "string" with format "byte".
Closes #53
=> Support []byte parameters and return type

integrationtest/package-lock.json, integrationtest/package.json
Bump fabric-chaincode-integration to 0.8.4
and update dependencies including axios.
=> Bump fabric-chaincode-integration to 0.8.4

integrationtest/package-lock.json, integrationtest/package.json
CVE-2025-7783 | update to form-data to 4.0.4
=> CVE-2025-7783 | update to form-data to 4.0.4
